#!/bin/bash
printf "# Makefile autogenerated\n\n";
printf "resolution = 403\n"
printf "logo = logo.png\n\n"

printf "N := x\n"
printf "C = \$(words \$N)\$(eval N := x \$N)\n"
printf "ECHO = echo -n \"\`expr \"   [\\\`expr \$C '*' 100 / \$T\\\`\" : '.*\\(....\\)\$\$'\`%%]\"\n"
printf "DONE = echo -n \"\`expr \"   [100\" : '.*\\(....\\)\$\$'\`%%]\"\n"
printf "\n"
